### ISSUE TITLE
Rewrite/verify structural analysis

### ISSUE THREAD

**Issue by jonpalmisc** [jonpalmisc/ObjectiveNinja#25]
I've recently learned of https://github.com/cxnder/ktool/blob/master/src/ktool/objc.py, which — unlike Objective Ninja — implements accurate analysis of Objective-C data in binaries. This is unsurprising considering that the current analysis is the product of my own (poor) reverse engineering.

**Update**: Refactoring is currently in progress on the [`rewrite`](https://github.com/jonpalmisc/ObjectiveNinja/tree/rewrite) branch.

## Tasks

- [x] Rewrite all structure analysis code
- [x] Remove old structure analysis, integrate new code with workflow
- [x] Fix/verify (tagged)pointer-decoding logic
- [x] Smoke test with lots of test binaries
- [x] Compare before/after output

**Comment by cxnder** [comment]
I am not familiar enough with writing C++ to make meaningful contributions to the code, however I'm actively working on a full proper site devoted to documenting the macho+objc+swift ABIs in detail, and can let you know when thats online.

The code in that linked file should *hopefully* be self documenting enough, to some extent, but feel free to reach out if you're confused about something or need help. objc abi is a big, undocumented pain.
